---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - values.yaml

patches:
  - target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: harbor
  patch: |-
   - values.yaml