---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  commonName: argocd.walletzk.app
  secretName: argocd-secret
  dnsNames:
    - argocd.walletzk.app
  issuerRef:**Re
    name: letsencrypt-prod
    kind: ClusterIssuer
