apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-secret
  namespace: harbor
spec:
  encryptedData:
    adminPassword: AgBi4YJBUuhIy5+QdUsTaf9cK3sK14hRnp15pBvWa9VE19mf1GhxI+hel/ZcyVXtp5Fh45dONO5wcxmuFjUlvng4yzvTCCB+SG/kn67yVcBJLKUhb5/2rCD96s86IqdNEznWJ9uignaFv5flnQd3MllhuSdKvNML/dt5sxsUtAOEhZfCJlr9PC9Xwg9kPPYqLgNOYkG0zPJ+Tsrw9QW+rjorhZ5TPtG1nREYbh+In5UblxtmuJw746ByMroGUKJcNp/FJZ0cXa+c9eKCp7BlPbd7bye8vtrHGKuyZdRnZUAATkG/Hw+EExvwkqE6UL9BhgrDJJ1qiYClzcZm9DmPDa2+7P24+39ix4IbndKnSt7kDiWT8lwXcrlWSscBpLRRVHsgDeTR8jZc1ixBZwQilJ1NLfVMkAwRyHeBKKzhqvr21lh9AergeKDWOfR+lqcpkW9MwUliBtx3YY2zqmxT1giAd6xHm+gmyXDfICPNM2syBkM1tPQOsSk8vAiD0CMKCxKrurfu54uburAfP/4L0iWuSa+aFjOOQYu/Q+/rFwhFUw3bE0Ltp4SNaNvrLdDTmX1r9SOT1fFPOtnn+lp0aNLxKWDTRBWDIgNJB1qtNvB++66JsGGRpU/ewLwgjf0NONT7QakO8lcf8bXlLobzFobz82Pr914KPf08hThbY+17wkMivQmYW3zWlkspAExSylvP95b9BqHJCkLS+G3tbkTNFfW/nuCObnCrv9lDgN4=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-secret
      namespace: harbor
